format:
  pdf:
    documentclass: scrreport
    highlight-style: arrow
    font-size: 13
    color-links: true
    links-as-notes: true
    citecolor: "blue"
    include-in-header: [latex/preamble-editing.tex]
    include-before-body: latex/before_body.tex 
    # geometry optimized for reading on ipad pro
    geometry:
      - paperwidth=214mm
      - paperheight=280mm
      - left=30mm
      - right=60mm
      - top=25mm
      - bottom=30mm 
