project:
  type: book
  resources:
    - privacy-policy.html
    - images/cover-sidepanel.jpg
  post-render:
    - ../scripts/redirect.py 
  output-dir: ../docs
  
execute:
  echo: false
  warning: false
  message: false
  cache: true
  fig-align: center

engine: knitr

book:
  title: "Machine Learning Interpretável"
  subtitle: "Um Guia para Tornar Modelos de Caixa-Preta Explicáveis"
  author: "Christoph Molnar"
  description: "Traduzido por: Mateus Toledo"
  output-file: iml
  favicon: images/favicon.jpg
  cookie-consent:
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-V7RTNZBGE2"
    anonymize-ip: true
  page-footer: |
    <a href="privacy-policy.html" target="_blank" style="font-size:11px;" > Privacy Policy </a> | <a href="https://christophmolnar.com/impressum" target="_blank" style="font-size:11px"> Impressum </a>
  repo-url: https://github.com/christophM/interpretable-ml-book
  repo-actions: [source, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - interpretability.qmd
    - goals.qmd
    - overview.qmd
    - data.qmd
    - part: "Modelos Interpretáveis"
      chapters:
        - limo.qmd
        - logistic.qmd
        - extend-lm.qmd
        - tree.qmd
        - rules.qmd
        - rulefit.qmd
    - part: "Métodos Locais Independentes de Modelo"
      chapters:
        - ceteris-paribus.qmd
        - ice.qmd
        - lime.qmd
        - counterfactual.qmd
        - anchors.qmd
        - shapley.qmd
        - shap.qmd
    - part: "Métodos Globais Independentes de Modelo"
      chapters:
        - pdp.qmd
        - ale.qmd
        - interaction.qmd
        - decomposition.qmd
        - feature-importance.qmd
        - lofo.qmd
        - global.qmd
        - proto.qmd
    - part: "Interpretação de Redes Neurais"
      chapters:
        - cnn-features.qmd
        - pixel-attribution.qmd
        - detecting-concepts.qmd
        - adversarial.qmd
        - influential.qmd
    - part: "Para Além dos Métodos" 
      chapters:
        - evaluation.qmd
        - storytime.qmd
        - future.qmd
        - translations.qmd
    - cite.qmd
    - acknowledgements.qmd
  appendices:
    - what-is-machine-learning.qmd
    - math-terms.qmd
    - r-packages.qmd
    - references.qmd

bibliography: [references.bib,grateful-refs.bib]
cite-method: citeproc

format:
  epub:
    lang: pt-BR
    html-math-method: webtex 
    highlight-style: printing
    always_allow_html: true
    css: html/epub.css
    description: "Algoritmos de aprendizado de máquina geralmente operam como caixas-pretas, e não está claro como eles chegam a determinada decisão. Este livro é um guia para profissionais que desejam tornar as decisões de aprendizado de máquina interpretáveis."
    toc-depth: 2
  pdf:
    documentclass: scrreprt 
    to-depth: 2
  html:
    lightbox: true
    cover-image: images/cover.jpg
    include-in-header: [html/purchase.html]
    page-layout: article 
    smooth-scroll: true
    theme: [cosmo, html/style.scss] 
    grid:
      sidebar-width: 370px
    fig-align: center
    number-depth: 0
    #reference-location: margin
    #citation-location: margin



