on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Build and deploy book

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KNITR_OPTIONS: "knitr.chunk.tidy=TRUE"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Configure Java for R
        run: |
          sudo R CMD javareconf

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libcurl4-openssl-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libcairo2-dev \
          libjpeg-dev \
          libgsl-dev

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Install tinytex
        run: |
          quarto install tinytex


      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with: 
          target: gh-pages
          path: manuscript/


